{% set version = "3.1.0" %}
{% set sha256 = "033db66659a8d2a54b20280c0f9036b7a173f397b5f07d3a214b1dde4d6b6058" %}

package:
  name: hhsuite
  version: {{ version }}

build:
  number: 1

source:
  url: https://github.com/soedinglab/hh-suite/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - openmp
    - perl
    - python

  run:
    - openmp

test:
  commands:
    - hhblits > /dev/null
    - hhsearch > /dev/null
    - hhalign > /dev/null

about:
  home: https://github.com/soedinglab/hh-suite
  license: GPLv3
  summary: "HH-suite3 for fast remote homology detection and deep protein annotation"
